name: health_journal
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_native_splash: ^2.4.4
  hive_local_storage: ^1.1.1
  path_provider: ^2.1.5
  fl_chart: ^0.66.2
  animations: ^2.0.11
  intl: ^0.18.0
  shimmer: ^3.0.0
  hive_flutter: ^1.1.0
  flutter_spinkit: ^5.2.1
  shared_preferences: ^2.3.2
  http: ^1.2.2
  hive: ^2.0.5

  smooth_page_indicator: ^1.2.0+3
  flutter_screenutil: ^5.9.3
  google_fonts: ^4.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.2"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  color_dark: "#ffffff"
  image_dark: "assets/logo.png"


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/

